#!/bin/bash

# $1 the search term; $2 the output file path

[ -e "$2" ] && exit 1

url="`curl -sG --connect-timeout 15 --data-urlencode "keyword=$1" "http://www.lrc123.com/" | grep -B1 '下载' | grep color | sed -n '1p' | sed 's/<[^>]*>//g;s/[[:space:]]//g'`"

if [ -n "$url" ]; then
    # download the lyrics
    lrc="`curl --connect-timeout 15 -s "$url" | iconv -f GBK`" 
    if [ -n "$lrc" ]; then 
       if [ -n "$2" ]; then 
           mkdir -p "`dirname "$2"`"
           echo "$lrc" > "$2" 
       else
           echo "$lrc"
       fi
    fi
fi
